export const ADD_COMMENT = 'ADD_COMMENT';

export const GET_TEN_APPLICATIONS = 'GET_TEN_APPLICATIONS';

export const GET_COUNT_AMOUNT = 'GET_COUNT_AMOUNT';

export const INPUT_FILTER_DATE_FROM = 'INPUT_FILTER_DATE_FROM';
export const INPUT_FILTER_DATE_TO = 'INPUT_FILTER_DATE_TO';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
