export const ADD_COMMENT = 'ADD_COMMENT';

export const GET_TEN_APPLICATIONS = 'GET_TEN_APPLICATIONS';

export const GET_COUNT_AMOUNT = 'GET_COUNT_AMOUNT';

export const INPUT_FILTER_DATE_FROM = 'INPUT_FILTER_DATE_FROM';
export const INPUT_FILTER_DATE_TO = 'INPUT_FILTER_DATE_TO';

export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';

export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT';
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE';
export const CHANGE_NUMBER = 'CHANGE_NUMBER';
export const INIT_FILTERS = 'INIT_FILTERS';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_ACTIVE_FILTERS = 'SET_ACTIVE_FILTERS';

export const SAVE_HASH = 'SAVE_HASH';
export const SAVE_ID = 'SAVE_ID';



